
import java.util.concurrent.LinkedBlockingQueue;

public class Grille extends javax.swing.JFrame {

    private final CasePanel[][] tabCP;
    private final Sudoku sudo;
    private LinkedBlockingQueue<String> messages;

    public Grille(Sudoku sudo) {
        tabCP = new CasePanel[9][9];
        this.sudo = sudo;
        messages = new LinkedBlockingQueue<>();
        initComponents();
        for (int i = 0; i < 9; ++i) {
            for (int j = 0; j < 9; ++j) {
                tabCP[i][j] = new CasePanel(sudo, i, j);
                tabCP[i][j].setBounds(i * 42 + (i / 3) * 3 + 3, j * 42
                        + (j / 3) * 3 + 3, 42, 42);
                jeuPanel.add(tabCP[i][j]);
            }
        }
        (new Thread() {
            public void run() {
                while (true) {
                    try {
                        String s = messages.take();
                        setEnabled(false);
                        for (CasePanel[] tcp : tabCP) {
                            for (CasePanel cp : tcp) {
                                cp.setEnabled(false);
                            }
                        }
                        texteTuteur.append("\nTuteur :\n   ");
                        Thread.sleep(300);
                        for (int i = 0; i < s.length(); i++) {
                            texteTuteur.append(String.valueOf(s.charAt(i)));
                            texteTuteur.setCaretPosition(texteTuteur.getText().length());

                            Thread.sleep(20);
                        }
                        Thread.sleep(500);
                        texteTuteur.append("\n");
                        texteTuteur.setCaretPosition(texteTuteur.getText().length());
                    } catch (InterruptedException e) {
                    }
                    setEnabled(true);
                }
            }
        }).start();
    }

    @Override
    public void setEnabled(boolean e) {
        for (CasePanel[] tcp : tabCP) {
            for (CasePanel cp : tcp) {
                cp.setEnabled(e);
            }
        }
    }

    public void ajouterMessage(String s) {
        messages.add(s);
    }

    public void effacerMessages() {
        texteTuteur.setText("");
    }

    public void erreurHypo(int ligne, int col, int valeur, boolean err) {
        tabCP[ligne][col].setErreurHypo(valeur, err);
    }

    public void erreurValeur(int ligne, int col, boolean err) {
        tabCP[ligne][col].setErreur(err);
    }

    public void setPuzzle(int[][] puzzle) {
        for (int i = 0; i < puzzle.length; ++i) {
            for (int j = 0; j < puzzle[i].length; ++j) {
                if (puzzle[i][j] != 0) {
                    tabCP[i][j].setValeur(puzzle[i][j], true);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jeuPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        texteTuteur = new javax.swing.JTextArea();
        indiceBouton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jeuPanel.setMinimumSize(new java.awt.Dimension(390, 390));

        javax.swing.GroupLayout jeuPanelLayout = new javax.swing.GroupLayout(jeuPanel);
        jeuPanel.setLayout(jeuPanelLayout);
        jeuPanelLayout.setHorizontalGroup(
            jeuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 713, Short.MAX_VALUE)
        );
        jeuPanelLayout.setVerticalGroup(
            jeuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        getContentPane().add(jeuPanel, java.awt.BorderLayout.CENTER);

        jPanel2.setMinimumSize(new java.awt.Dimension(300, 300));
        jPanel2.setName(""); // NOI18N

        texteTuteur.setEditable(false);
        texteTuteur.setColumns(20);
        texteTuteur.setRows(5);
        texteTuteur.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(texteTuteur);

        indiceBouton.setText("indice");
        indiceBouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indiceBoutonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(indiceBouton)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(indiceBouton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void indiceBoutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indiceBoutonActionPerformed
        sudo.afficherIndice();
    }//GEN-LAST:event_indiceBoutonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton indiceBouton;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jeuPanel;
    private javax.swing.JTextArea texteTuteur;
    // End of variables declaration//GEN-END:variables
}
